import {rules,slideOrder,abbreviations,datasets,classify,metrics,parseExcerpt} from './model.js';
const $=id=>document.getElementById(id),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let order=['period'],active='slides',customLines=[],selected=null,attempts=[],lastResult=[];
const findRule=id=>rules.find(r=>r.id===id),name=id=>findRule(id).title;
const outcome={tp:'Correct EOS',fp:'Wrong EOS',fn:'Missed EOS',tn:'Correctly not EOS'};
const format=n=>n===null?'—':Math.round(n*100)+'%';
function getLines(){return active==='custom'?customLines:datasets.find(d=>d.id===active).lines;}
function renderRules(focusId){
 $('ruleChoices').innerHTML=rules.map(r=>`<label class="eos-rule-choice"><input id="choose-${r.id}" type="checkbox" data-rule="${r.id}" ${order.includes(r.id)?'checked':''}><span><strong>${r.title}</strong><small>If yes → ${r.label?'EOS':'not EOS'}. ${r.description}</small></span></label>`).join('');
 $('orderedRules').innerHTML=order.map((id,i)=>`<li class="eos-ordered"><div class="eos-ordered-title">${name(id)} → ${findRule(id).label?'EOS':'not EOS'}</div><div class="eos-ordered-controls"><button id="up-${id}" data-move="${id}" data-direction="-1" ${i===0?'disabled':''} aria-label="Move ${name(id)} up">↑ Up</button><button id="down-${id}" data-move="${id}" data-direction="1" ${i===order.length-1?'disabled':''} aria-label="Move ${name(id)} down">↓ Down</button><button data-remove="${id}" aria-label="Remove ${name(id)}">Remove</button></div></li>`).join('')||'<li class="eos-small">No rules selected. Every word receives the default “not EOS.”</li>';
 renderPredictions();if(focusId){const el=$(focusId);if(el&&!el.disabled)el.focus();else if(focusId.startsWith('up-'))$('down-'+focusId.slice(3))?.focus();else if(focusId.startsWith('down-'))$('up-'+focusId.slice(5))?.focus();}
}
function renderPredictions(){
 const show=$('feedback').checked;lastResult=classify(getLines(),order);
 $('datasetNote').textContent=active==='custom'?'Your | markers supply the reference EOS labels. Rules receive only the text and its observable features.':datasets.find(d=>d.id===active).note;
 $('legend').innerHTML=show?'<span class="tp">✓ Correct EOS prediction</span><span class="fp">× Wrong EOS prediction</span><span class="fn">! Missed true ending</span>':'<span class="predicted">EOS prediction</span><span>Correctness feedback hidden</span>';
 $('predictions').innerHTML=lastResult.map((tokens,i)=>`<div class="eos-excerpt"><div class="eos-excerpt-number">EXCERPT ${i+1}</div><div class="eos-words">${tokens.map((t,j)=>{const cls=show?t.status:t.prediction.label?'predicted':'tn',badge=show?({tp:'✓ EOS',fp:'× EOS',fn:'! Missed'})[t.status]:t.prediction.label?'EOS':null;return `<button class="eos-token ${cls}" data-excerpt="${i}" data-token="${j}" aria-pressed="${!!selected&&selected[0]===i&&selected[1]===j}" aria-label="${escape(t.text)}: ${show?outcome[t.status]:t.prediction.label?'predicted EOS':'predicted not EOS'}">${escape(t.text)}${badge?`<span class="eos-badge">${badge}</span>`:''}</button>`;}).join(' ')}</div></div>`).join('');
 const s=metrics(lastResult);$('scores').innerHTML=show?[[s.tp,'Correct EOS'],[s.fp,'Wrong EOS'],[s.fn,'Missed EOS'],[format(s.precision),'EOS precision'],[format(s.recall),'EOS recall']].map(([v,l])=>`<div><strong>${v}</strong><span>${l}</span></div>`).join(''):`<p>${s.tp+s.fp} words predicted as EOS. Turn on correctness feedback to check them.</p>`;renderTrace();
}
function renderTrace(){
 if(!selected){$('trace').textContent='Click a word above. The rule trace will appear here.';return;}
 const t=lastResult[selected[0]]?.[selected[1]];if(!t){selected=null;renderTrace();return;}const show=$('feedback').checked;
 $('trace').innerHTML=`<h3>“${escape(t.text)}” · Excerpt ${selected[0]+1}, word ${selected[1]+1}</h3><p class="eos-verdict ${show?t.status:t.prediction.label?'predicted':'tn'}"><strong>Predicted: ${t.prediction.label?'EOS':'not EOS'}</strong>${show?` · Reference: ${t.gold?'EOS':'not EOS'}<br>${outcome[t.status]}`:''}</p><p class="eos-features">${rules.map(r=>`${r.title}: <strong>${t.features[r.id]?'yes':'no'}</strong>`).join(' · ')}</p><ol class="eos-trace-list">${t.prediction.trace.map(step=>`<li class="${!step.reached?'eos-notreached':step.matches?'eos-fired':''}">${name(step.id)}? ${!step.reached?'Not reached: an earlier rule already decided.':step.matches?`Yes → ${findRule(step.id).label?'EOS':'not EOS'}. Stop here.`:'No → continue.'}</li>`).join('')}</ol>${t.prediction.rule===null?'<p><strong>No selected rule matched → default: not EOS.</strong></p>':''}`;
}
$('ruleChoices').addEventListener('change',e=>{const id=e.target.dataset.rule;if(!id)return;order=e.target.checked?[...order,id]:order.filter(x=>x!==id);renderRules('choose-'+id);});
$('orderedRules').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.remove){order=order.filter(x=>x!==b.dataset.remove);renderRules('choose-'+b.dataset.remove);}else if(b.dataset.move){const i=order.indexOf(b.dataset.move),j=i+Number(b.dataset.direction);if(j<0||j>=order.length)return;[order[i],order[j]]=[order[j],order[i]];renderRules(b.id);}});
$('selectAll').onclick=()=>{order=[...order,...rules.map(r=>r.id).filter(id=>!order.includes(id))];renderRules();};
$('clear').onclick=()=>{order=[];renderRules();};$('slideRules').onclick=()=>{order=[...slideOrder];renderRules();};$('periodFirst').onclick=()=>{order=['period','last','terminal','abbreviation'];renderRules();};
$('feedback').onchange=()=>{renderPredictions();renderAttempts();};
$('predictions').addEventListener('click',e=>{const b=e.target.closest('[data-token]');if(!b)return;selected=[Number(b.dataset.excerpt),Number(b.dataset.token)];$('predictions').querySelectorAll('[data-token]').forEach(el=>el.setAttribute('aria-pressed',el===b?'true':'false'));renderTrace();});
function applyCustom(){try{const lines=$('customText').value.split(/\n/u).map(s=>s.trim()).filter(Boolean);if(!lines.length)throw new Error('Enter at least one excerpt.');if(lines.join(' ').length>12000)throw new Error('Please use fewer than 12,000 characters.');lines.forEach(parseExcerpt);customLines=lines;selected=null;$('customFeedback').textContent='Applied. Check your reference markers if a correctness label looks unexpected.';renderPredictions();}catch(e){$('customFeedback').textContent=e.message;}}
$('dataset').onchange=()=>{active=$('dataset').value;selected=null;$('customPanel').hidden=active!=='custom';if(active==='custom')applyCustom();else renderPredictions();};$('applyCustom').onclick=applyCustom;
$('record').onclick=()=>{const s=metrics(lastResult);attempts.push({name:active==='custom'?'Custom text':datasets.find(d=>d.id===active).name,lines:[...getLines()],order:[...order],scores:s});renderAttempts();};
function renderAttempts(){const show=$('feedback').checked;$('attempts').innerHTML=attempts.length?`<table><thead><tr><th>Attempt & text</th><th>Rule order</th><th>Correct EOS</th><th>Wrong EOS</th><th>Missed EOS</th><th></th></tr></thead><tbody>${attempts.map((a,i)=>`<tr><td>${i+1}. ${escape(a.name)}</td><td>${a.order.map(name).join(' → ')||'None (default only)'}</td><td>${show?a.scores.tp:'Hidden'}</td><td>${show?a.scores.fp:'Hidden'}</td><td>${show?a.scores.fn:'Hidden'}</td><td><button data-restore="${i}">Restore</button></td></tr>`).join('')}</tbody></table>`:'<p class="eos-small">No attempts saved yet.</p>';}
$('attempts').addEventListener('click',e=>{const b=e.target.closest('[data-restore]');if(!b)return;const a=attempts[Number(b.dataset.restore)];order=[...a.order];const d=datasets.find(d=>d.name===a.name);active=d?d.id:'custom';$('dataset').value=active;$('customPanel').hidden=active!=='custom';if(active==='custom'){customLines=[...a.lines];$('customText').value=a.lines.join('\n');}selected=null;renderRules();});
$('export').onclick=()=>{const current={order,lines:getLines(),scores:metrics(lastResult)};let text='SENTENCE-ENDING CLASSIFICATION LAB\n\n';for(const [i,a]of [...attempts,{...current,name:'Current setting'}].entries()){text+=`${i+1}. ${a.name}\nRules: ${a.order.map(id=>name(id)+' → '+(findRule(id).label?'EOS':'not EOS')).join('; ')||'None'}\nText and reference markers:\n${a.lines.join('\n')}\n`;if($('feedback').checked)text+=`Correct EOS: ${a.scores.tp}; wrong EOS: ${a.scores.fp}; missed EOS: ${a.scores.fn}; precision: ${format(a.scores.precision)}; recall: ${format(a.scores.recall)}\n`;text+='\n';}const url=URL.createObjectURL(new Blob([text],{type:'text/plain'})),a=document.createElement('a');a.href=url;a.download='sentence-ending-lab-attempts.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('abbreviations').textContent=abbreviations.join(', ');renderRules();
